name: Deploy-Production

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
    types: ['closed']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DEPLOY_PROD

    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .env
        run: echo "${{secrets.ENV}}" > .env

      - name: Install Dependencies
        run: npm ci

      - name: Build Production
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_PROD_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_PROD_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Deploy to AWS S3
        env:
          BUCKET_NAME: ${{secrets.AWS_PROD_BUCKET_NAME}}
          aws-access-key-id: ${{secrets.AWS_PROD_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_PROD_SECRET_ACCESS_KEY}}
        run: aws s3 sync ./dist s3://$BUCKET_NAME --delete

      - name: Invalidate AWS Cloudfront Cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{secrets.AWS_PROD_CLOUDFRONT_ID}} --paths "/*"

  rebase:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    permissions: 
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout develop branch
        run: git checkout develop

      - name: Rebase develop onto main
        run: git rebase origin/main

      - name: Force Push updated develop branch
        run: git push origin develop --force-with-lease
