name: Deploy-Development

on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
    types: ['closed']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DEPLOY_DEV

    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .env
        run: echo "${{secrets.ENV}}" > .env

      - name: Print whether share mode is enabled
        run: echo "VITE_ENABLE_SHARE_URL=$VITE_ENABLE_SHARE_URL"

      - name: Install Dependencies
        run: npm ci

      - name: Build Development
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_DEV_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_DEV_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Deploy to AWS S3
        env:
          BUCKET_NAME: ${{secrets.AWS_DEV_BUCKET_NAME}}
          aws-access-key-id: ${{secrets.AWS_DEV_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_DEV_SECRET_ACCESS_KEY}}
        run: aws s3 sync ./dist s3://$BUCKET_NAME --delete

      - name: Invalidate AWS Cloudfront Cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{secrets.AWS_DEV_CLOUDFRONT_ID}} --paths "/*"
