name: Discord notification on new issues

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      issue_title:
        description: '이슈의 제목'
        required: true
        default: '[TEST] GitHub Actions 테스트용 가짜 이슈'
      issue_body:
        description: '이슈의 내용'
        required: true
        default: |
          # 이슈 내용
          - 가짜 이슈 1 해결
          - 가짜 이슈 2 해결

          # 마감 기간
          - 오늘
      issue_url:
        description: 'Issue URL'
        required: true
        default: 'https://github.com/debate-timer/debate-timer/fe/issues/1'
      author_name:
        description: '작성자 이름'
        required: true
        default: '테스트 작성자'
      author_url:
        description: '작성자 링크'
        required: true
        default: 'http://www.naver.com'

jobs:
  notify-discord-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Debug All Event Data
        run: echo '${{ toJson(github.event) }}'

      - name: Set Environment Variables
        env:
          TITLE: ${{ github.event.issue.title }}
        run: |
          echo "AVATAR_URL=${{ secrets.DISCORD_AVATAR_URL }}" >> $GITHUB_ENV
          echo "USERNAME=망곰" >> $GITHUB_ENV
          echo "CONTENT=새 이슈가 생겼어요!" >> $GITHUB_ENV
          echo "WEB_HOOK=${{ secrets.DISCORD_WEB_HOOK }}" >> $GITHUB_ENV

      - name: Notify Discord
        env:
          # AUTHOR_NAME: ${{ github.event.issue.user.login }}
          # ISSUE_URL: ${{ github.event.issue.html_url }}
          # ISSUE_TITLE: ${{ github.event.issue.title }}
          # AUTHOR_URL: ${{ github.event.issue.user.avatar_url }}
          # ISSUE_BODY: ${{ github.event.issue.body }}
          AUTHOR_NAME: ${{ github.action.inputs.author_name }}
          ISSUE_URL: ${{ github.action.inputs.issue_url }}
          ISSUE_TITLE: ${{ github.action.inputs.issue_title }}
          AUTHOR_URL: ${{ github.action.inputs.author_url }}
          ISSUE_BODY: ${{ github.action.inputs.issue_body }}
          AVATAR_URL: ${{ env.AVATAR_URL }}
          USERNAME: ${{ env.USERNAME }}
          WEB_HOOK: ${{ env.WEB_HOOK }}
          CONTENT: ${{ env.CONTENT }}
        run: |
          if [ -n "$WEB_HOOK" ]; then
            JSON_PAYLOAD=$(jq -n \
              --arg content "$CONTENT" \
              --arg username "$USERNAME" \
              --arg avatar_url "$AVATAR_URL" \
              --arg issue_title "$ISSUE_TITLE" \
              --arg issue_url "$ISSUE_URL" \
              --arg author_url "$AUTHOR_URL" \
              --arg author_name "$AUTHOR_NAME" \
              --arg color "5814783" \
              --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
              '{
                username: $username,
                avatar_url: $avatar_url,
                content: $content,
                embeds: [{
                  title: $issue_title,
                  url: $issue_url,
                  author: {
                    name: $author_name,
                    icon_url: $author_url
                  },
                  color: ($color | tonumber),
                  timestamp: $timestamp
                }]
              }')

            curl -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$WEB_HOOK"
          else
            echo "No matching title found. Skipping notification."
          fi
